-- =====================================================================
-- Traductions françaises des 16 expériences publiées (experiences2)
-- Exécuter dans Supabase > SQL Editor > New query > Run
-- Résultat attendu : 16 rows affected
-- =====================================================================

-- 1. BLACK GOLD RITUAL AT THE DEAD SEA
UPDATE experiences2 SET
  title_fr = 'Rituel de la Boue Noire, Mer Morte',
  subtitle_fr = 'Le rituel minéral le plus connu du monde, dans les eaux les plus denses de la Terre.',
  long_copy_fr = '<p>Un rituel de bien-être né il y a des millénaires, sur les rives de la Mer Morte. La boue noire est chargée en minéraux : magnésium, potassium, calcium, bromure. On l''applique sur tout le corps. Elle sèche au soleil. La peau chauffe. On la rince dans l''eau salée de la Mer Morte. Ce qui reste est une peau douce comme elle ne l''a pas été depuis des années.</p><p>La Mer Morte est à 430 mètres sous le niveau de la mer, le point le plus bas de la surface de la Terre. La densité de l''eau est si élevée que flotter ne demande aucun effort. On se laisse aller et le sel vous tient. Les jambes remontent d''elles-mêmes. On dérive, les bras en croix, en regardant le ciel bleu et les falaises jordaniennes à l''horizon.</p><p>La journée commence sur la plage privée du resort. Les soins de boue sont disponibles sur la plage ou au spa. Un soin type comprend : une enveloppe de boue noire, un bain thermal dans l''eau de la Mer Morte, un gommage au sel et un massage à l''huile de lavande. Entre les soins, on se repose sur les transats. Le rythme est entièrement le sien.</p><p>Le resort est construit face à l''eau. Les chambres donnent sur la Mer Morte et les montagnes jordaniennes. Le dîner est une cuisine méditerranéenne légère, poissons du jour, légumes locaux, vins israéliens. Le lendemain matin, on peut retourner flotter. La plupart des gens le font. Il y a quelque chose dans cette eau qui appelle à revenir.</p>'
WHERE slug = 'black-gold-ritual-dead-sea';

-- 2. CANDLELIGHT CONCERT (Coldplay & Imagine Dragons)
UPDATE experiences2 SET
  title_fr = 'Concert aux Chandelles, Tel Aviv',
  subtitle_fr = 'Les plus grands titres de Coldplay et Imagine Dragons réinterprétés pour quatuor à cordes, à la lumière des bougies dans un lieu historique de Tel Aviv.',
  long_copy_fr = '<p>Un concert dans un bâtiment du XIXe siècle au coeur de Tel Aviv, éclairé aux bougies. Un quatuor à cordes interprète les titres les plus marquants de Coldplay et Imagine Dragons, entièrement réarrangés pour violons, alto et violoncelle. Fix You, The Scientist, Viva la Vida, Radioactive, Believer. Des chansons qu''on connaît par coeur, dans une version qu''on n''a jamais entendue.</p><p>La salle accueille environ 250 personnes. Les places sont en libre accès, premier arrivé premier servi. Si vous voulez être près des musiciens, arrivez tôt. L''espace fait partie de l''expérience : les murs sont sombres, la lueur des bougies vacille sur les visages, et le son semble venir de partout à la fois. Le concert dure environ quatre-vingt-dix minutes, sans entracte.</p><p>Il se passe quelque chose d''inattendu quand des chansons rock passent par les cordes et les bougies. L''électricité devient quelque chose de plus calme. Les mélodies qu''on avait déjà entendues mille fois se révèlent autrement. La salle chante parfois, doucement, sans qu''on lui ait demandé.</p><p>Après le concert, des restaurants ouverts tard sont accessibles à pied. L''hôtel est à quelques minutes. Le lendemain matin a un autre goût après une nuit de lumière et de cordes.</p>'
WHERE slug = 'candlelight-concert-coldplay-imagine-dragons-tel-aviv';

-- 3. CINEMA NIGHT AT POLI HOUSE
UPDATE experiences2 SET
  title_fr = 'Nuit cinéma à Poli House, Tel Aviv',
  subtitle_fr = 'Une projection intime d''un film soigneusement choisi dans une maison historique de Tel Aviv, suivie d''un séjour au coeur de la ville.',
  long_copy_fr = '<p>Movie Night à Poli House est une projection privée dans une maison restaurée des années 1920 à Tel Aviv. Un seul film, soigneusement choisi, projeté sur grand écran dans un cadre intimiste. Cinquante personnes maximum. Pas de téléphone, pas de distractions. Juste le film et l''espace.</p><p>La maison est dans le quartier de Poli Street, dans un coin de Tel Aviv qui garde encore l''atmosphère du vieux Tel Aviv. La façade est d''origine. L''intérieur a été restauré pour honorer l''époque tout en apportant le confort moderne. La salle de projection est à l''étage, avec des poutres en bois d''origine et une grande fenêtre en arche qui donne sur la rue en contrebas.</p><p>La sélection des films change chaque mois. Les thèmes varient : parfois une restauration d''un classique, parfois une oeuvre contemporaine, parfois un documentaire. Les choix du programmateur sont toujours réfléchis. L''objectif n''est pas seulement le divertissement, mais une expérience. Le film dure généralement entre 90 et 120 minutes. Après la projection, une brève discussion est animée par quelqu''un qui connaît bien le film ou son contexte.</p><p>Le dîner commence à 18h au restaurant du rez-de-chaussée. Il est en menu fixe, pensé en lien avec le film du soir. Le repas est lent. La conversation est encouragée. Le temps que le film commence à 20h, une communauté s''est formée : cinquante inconnus qui partagent la volonté de s''asseoir dans le noir et de faire attention pendant deux heures.</p><p>L''hébergement est dans un hôtel boutique dans la même rue. Les chambres sont simples, modernes, avec de hauts plafonds et de grandes fenêtres sur la rue. Le boulevard Rothschild est à un pâté de maisons. Le marché du Carmel, la plage et les musées sont tous accessibles à pied.</p>'
WHERE slug = 'movie-night-poli-house';

-- 4. DRINK & PAINT AT SUNSET
UPDATE experiences2 SET
  title_fr = 'Peindre et trinquer au coucher du soleil, Kinneret',
  subtitle_fr = 'Un atelier peinture au bord du Kinneret à l''heure dorée, verre de vin à la main, suivi d''une soirée de musique live à Lake House.',
  long_copy_fr = '<p>Un atelier peinture au bord du Kinneret à l''heure dorée, avec du vin. Aucune expérience requise. Le postulat de Lake House est que tout le monde est créatif, et que la créativité a surtout besoin de permission et d''un bon endroit.</p><p>On arrive l''après-midi. La maison est grande et ouverte, avec de hauts plafonds et des fenêtres face au lac. Il y a un atelier peinture à l''étage, avec des chevalets, des peintures et des toiles. Un grand jardin face à l''eau.</p><p>Au coucher du soleil, le groupe s''installe dehors avec les toiles, les pinceaux et les verres. La lumière change vite au-dessus du Kinneret. Ce qu''on peint n''a pas besoin de ressembler à quoi que ce soit. Le vin aide. L''air du soir aide encore plus.</p><p>Après le dîner, préparé sur place avec des ingrédients locaux, une session de musique live a commencé dans la salle principale. L''espace est intime. Pas de scène, pas de séparation entre l''interprète et l''auditeur. Les espaces restent ouverts aussi longtemps que ça continue.</p><p>Le matin, le petit-déjeuner est à 8h sur la pelouse face au lac. Certains repartent avec une toile. D''autres avec le souvenir d''une chanson entendue dans le noir. L''essentiel n''est pas l''objet fini.</p>'
WHERE slug = 'paint-play-lake-house-kinneret';

-- 5. FAMILY ADVENTURE IN EILAT
UPDATE experiences2 SET
  title_fr = 'Aventure en famille à Eilat',
  subtitle_fr = 'Une journée de plongée en apnée, d''exploration du désert et de plage au bord de la mer Rouge, dans un resort familial.',
  long_copy_fr = '<p>Une journée complète entre eau et désert pour les familles avec des enfants à partir de 4 ans. Le rythme est conçu pour que ce soient les enfants qui mènent la danse, et les adultes qui bénéficient de les suivre.</p><p>La journée commence sur la plage avec une initiation au snorkeling pour ceux qui n''en ont jamais fait. L''eau à Eilat est chaude, transparente et pleine de poissons. Le guide montre aux enfants comment respirer avec le tuba, comment se déplacer lentement pour ne pas faire fuir les poissons. La plupart prennent ça immédiatement. Ceux qui ne sont pas à l''aise ont le choix de rester sur la plage et d''explorer les cuvettes rocheuses.</p><p>En milieu de matinée, le groupe se déplace vers une crique calme où le snorkeling est plus varié. Les enfants sont accompagnés par des adultes et ont le temps d''explorer à leur propre rythme. Le guide pointe certains poissons, explique ce qu''ils mangent, où ils se cachent le jour. À midi, tout le monde est fatigué et affamé.</p><p>Le déjeuner est un pique-nique sur la plage : sandwichs, fruits, jus pour les enfants, café pour les adultes. L''après-midi est libre : certaines familles nagent, d''autres construisent des châteaux de sable, d''autres se reposent sous les parasols.</p><p>À 16h, une courte balade en jeep emmène tout le monde dans le désert proche. Le guide explique les plantes qui survivent ici, les animaux qui chassent la nuit, le silence particulier du désert au crépuscule. Les enfants trouvent souvent des pierres en forme d''animaux. Il faut peu de choses pour enchanter un enfant.</p><p>À 17h30, tout le monde est de retour à l''hôtel. Le dîner est disponible au restaurant avec menu enfants et cuisine complète. La plupart des familles dorment avant 20h30.</p>'
WHERE slug = 'family-adventure-eilat';

-- 6. FOREST RESET AT BAYIT BAGALIL
UPDATE experiences2 SET
  title_fr = 'Ressourcement en forêt, Bayit BaGalil',
  subtitle_fr = 'Une nuit de retraite dans une maison rurale de Galilée, autour du ralentissement et de la reconnexion à soi, avec repas et balade guidée en forêt.',
  long_copy_fr = '<p>Une nuit dans une maison restaurée de Galilée rurale, conçue explicitement pour ralentir. Pas d''agenda au-delà des repas et de la balade en forêt. Personne pour vous demander d''être productif. Les appareils ne sont pas encouragés. Toute la structure est bâtie sur l''idée que vous avez besoin de repos.</p><p>On arrive en fin d''après-midi. La maison est installée sur plusieurs hectares entourés de forêt. Une tasse de thé vous attend. Quelqu''un vous montre votre chambre. Simple : un lit, une fenêtre sur la forêt, une petite table. Rien de superflu. On peut se reposer, lire, ou s''asseoir sur la véranda.</p><p>Le dîner est servi à 18h, en famille, autour d''une grande table. La nourriture est végétarienne, préparée avec des ingrédients locaux. Du vin si on le souhaite. Le repas est lent. La conversation est douce. À 20h, la plupart des gens sont retournés dans leurs chambres.</p><p>Le lendemain matin à 7h, un guide conduit une balade en forêt. L''allure est lente. Le guide s''arrête souvent pour désigner des plantes, expliquer l''écosystème, permettre à chacun de simplement rester là et d''écouter. La balade dure environ quatre-vingt-dix minutes. Au retour, le système nerveux a changé de régime. Les pensées sont plus calmes.</p><p>Le petit-déjeuner est à 9h : pain frais, fromage, fruits, café, miel. Servi sur la véranda face à la forêt. Pas de hâte. On peut s''attarder aussi longtemps qu''on veut.</p>'
WHERE slug = 'forest-reset-bayit-bagalil';

-- 7. GALILEE COUPLE'S SPA RITUAL (duo massage at the Setai)
UPDATE experiences2 SET
  title_fr = 'Rituel spa en duo, Setai Tel Aviv',
  subtitle_fr = 'Un soin pour deux dans le spa du Setai, au coeur de la vieille ville de Jaffa, suivi d''un séjour dans l''un des hôtels les plus remarquables de Tel Aviv.',
  long_copy_fr = '<p>Un massage en duo dans le spa du Setai, à Jaffa. Deux tables côte à côte, deux thérapeutes, un soin conçu pour deux personnes qui souhaitent décrocher ensemble plutôt que chacune de son côté.</p><p>Le Setai est installé dans des bâtiments ottomans du XIXe siècle sur la côte de Jaffa, face à la Méditerranée. Le spa est dans les parties les plus anciennes de la structure : des voûtes en pierre, une lumière tamisée, des couloirs qui ressemblent à une autre époque. Avant le soin, on vous conduit vers un hammam privatif pour une session de vapeur. Le corps commence à se détendre avant même que les mains des thérapeutes n''entrent en contact.</p><p>Le soin dure quatre-vingt-dix minutes. Le protocole associe des techniques de massage suédois et de pression des points d''acupression. L''huile est choisie en fonction des préférences : eucalyptus pour la clarté, lavande pour le calme, jasmin pour quelque chose de plus doux. Pas de conversation obligatoire. Le silence est possible.</p><p>Après le soin, on vous conduit vers un salon privatif avec des boissons chaudes et des fruits. On peut y rester aussi longtemps qu''on le souhaite. Ce temps de retour dans le corps fait partie de l''expérience.</p><p>Les chambres du Setai sont dans les anciennes ailes ottomanes. Les murs sont épais. Le silence est réel. Le restaurant du rez-de-chaussée sert une cuisine méditerranéenne élaborée. La plage est à deux minutes à pied. Ce qui est rare dans un séjour de ce genre, c''est qu''on n''a pas envie d''aller ailleurs.</p>'
WHERE slug = 'a-duo-massage-at-the-setai';

-- 8. GOLDEN HOUR DINNER IN OLD JAFFA
UPDATE experiences2 SET
  title_fr = 'Dîner à l''heure dorée, Vieille Jaffa',
  subtitle_fr = 'Une table avec vue sur la Méditerranée au coucher du soleil, au restaurant du Setai dans la vieille ville de Jaffa, suivi d''une nuit dans l''hôtel.',
  long_copy_fr = '<p>Un dîner au Setai à Jaffa, au moment où la lumière de la Méditerranée est la meilleure. La salle à manger est installée dans les murs ottomans du XIXe siècle, avec des ouvertures sur la mer. À 18h30, la lumière entre en oblique. À 19h, elle est dorée. À 19h30, elle est orange. À 20h, il fait nuit et les bougies ont pris le relais.</p><p>Le restaurant propose une cuisine méditerranéenne élaborée avec des références du Moyen-Orient. Poissons pêchés le jour, légumes du marché de Jaffa, épices d''une ville qui a toujours été à l''intersection des routes commerciales. La carte change selon les saisons.</p><p>Le menu dégustation est la façon la plus complète d''explorer la cuisine du chef. Il comprend six services et une sélection de vins israéliens et importés. Le sommelier propose des accords mets-vins à chaque service. On peut aussi commander à la carte si on préfère choisir.</p><p>Le service est discret mais présent. Les tables sont espacées. La salle n''est pas bondée. Les conversations restent privées. Le type d''endroit où on peut rester deux heures sans que personne ne vous regarde d''une façon qui signifie qu''il faudrait libérer la table.</p><p>Après le dîner, Jaffa s''offre à la promenade. Les ruelles de la vieille ville sont à quelques minutes. La mer est en bas. L''hôtel est à l''intérieur des mêmes murs ottomans. Se coucher dans un bâtiment du XIXe siècle après un dîner de ce genre, avec le son de la mer, c''est une manière particulièrement agréable de terminer une journée.</p>'
WHERE slug = 'sunset-dinner-old-jaffa-setai';

-- 9. JAPAN TASTE
UPDATE experiences2 SET
  title_fr = 'Saveurs du Japon, Ink Hotel Tel Aviv',
  subtitle_fr = 'Un dîner japonais raffiné au restaurant Sun Young, dans l''Ink Hotel au coeur de Tel Aviv, suivi d''une nuit dans un design hotel primé.',
  long_copy_fr = '<p>Un dîner japonais dans un design hôtel au coeur de Tel Aviv. Le restaurant Sun Young, installé au rez-de-chaussée de l''Ink Hotel, propose une cuisine japonaise contemporaine pensée par un chef formé à Tokyo. Les produits sont sourcés localement quand c''est possible, importés du Japon quand c''est nécessaire.</p><p>La carte tourne autour du poisson cru, des bouillons longs et des cuissons précises. Sashimis de thon rouge et de maquereau de la Méditerranée. Maki de riz vinaigré roulés devant vous au comptoir. Ramen de poulet cuit douze heures, avec des oeufs marinés et du bambou. Gyoza grillés. Une liste de saké et de whisky japonais.</p><p>L''espace est long et sombre, avec un comptoir de sushi ouvert sur la cuisine. On peut s''asseoir au comptoir et regarder travailler les cuisiniers, ou choisir une table. La lumière est basse. La musique est légère. L''ambiance est celle d''un izakaya de quartier transposé dans un hôtel de design.</p><p>L''Ink Hotel est l''un des hôtels les plus remarqués de Tel Aviv depuis son ouverture. Le bâtiment est un exemple d''architecture brutaliste réhabilitée, avec des matériaux bruts et des pièces d''art dans les espaces communs. La terrasse de la piscine sur le toit offre une vue sur la ville et la mer.</p><p>Après le dîner, le bar de l''Ink est l''endroit pour un dernier verre. La playlist change en soirée. Pour ceux qui souhaitent rentrer tôt, les chambres insonorisées permettent de dormir sans restriction.</p>'
WHERE slug = 'japanese-dinner-sun-young-ink-hotel-tel-aviv';

-- 10. JEEP TOUR AT TIMNA PARK
UPDATE experiences2 SET
  title_fr = 'Circuit en jeep, Parc de Timna',
  subtitle_fr = 'Une aventure en jeep guidée à travers les paysages cuivrés millénaires du parc de Timna, suivie d''un séjour à Play Eilat, à deux pas de la promenade nord de la mer Rouge.',
  long_copy_fr = '<p>Un circuit en jeep dans le parc de Timna, à 25 kilomètres au nord d''Eilat. Six mille ans de désert cuivré, et le genre de silence qui réorganise quelque chose en soi.</p><p>Le guide vous récupère au Play Eilat et prend la direction nord dans la vallée de l''Arava. À l''intérieur du parc, le paysage bascule dans quelque chose de plus ancien et de plus calme. Des colonnes de grès s''élèvent du fond de la vallée. Des rochers en forme de champignons, des arches, des sculptures naturelles façonnées par le vent depuis des millénaires. Le guide lit la géologie et l''histoire à voix haute, sans script.</p><p>On s''arrête aux Colonnes de Salomon, on monte la colline Borg, on longe les rives du lac Timna. Il y a un moment au niveau du sable coloré où tout le monde fait la même chose : remplir un petit flacon, lentement, en silence.</p><p>De retour à Eilat, le Play Eilat prend le relais pour le reste de la journée. La piscine extérieure, le bar au bord de l''eau, l''après-midi sans pression. L''hôtel est proche de la plage Hananya et de la promenade nord, assez calme pour décompresser, assez bien situé pour rejoindre l''animation le soir venu.</p><p>Le petit-déjeuner est un buffet complet, et la lumière de l''Arava entre tôt. Le genre de matin qui rend le trajet du retour, brièvement, difficile à envisager.</p>'
WHERE slug = 'jeep-tour-timna-park-play-eilat';

-- 11. JERUSALEM FROM ABOVE
UPDATE experiences2 SET
  title_fr = 'Jérusalem vue du ciel',
  subtitle_fr = 'La plus longue tyrolienne d''Israël au-dessus de la Vieille Ville de Jérusalem, suivie d''un séjour à l''Inbal Jérusalem, à deux pas des remparts.',
  long_copy_fr = '<p>La plus longue tyrolienne d''Israël, lancée depuis la Promenade de Jérusalem. La Vieille Ville en contrebas, 731 mètres devant soi.</p><p>Le point de départ est Mitzpe David, le centre de visite de la Cité de David sur la Promenade Armon Hanatziv, l''un des points culminants de Jérusalem. De là, la ville s''ouvre dans toutes les directions. La pierre ancienne, l''éclat du Dôme du Rocher, les remparts de la Vieille Ville qui s''effacent sous vos pieds. On vous harnache, la ligne est attachée, et vous partez. Sept cent trente et un mètres en vol au-dessus du paysage, avec le vent et le panorama complet de Jérusalem devant soi. La course se termine dans la Forêt de la Paix, une navette vous ramène au point de départ. Tout cela prend moins d''une heure. Ce que ça fait dure plus longtemps.</p><p>Puis on remonte à pied vers l''Inbal. L''hôtel fait face au parc de la Cloche de la Liberté, avec une vue directe sur les remparts. Le Mur occidental est à dix minutes à pied. La Porte de Jaffa est encore plus proche. Après l''adrénaline, l''hôtel vous accueille avec discrétion : des chambres larges, un spa en bas, une piscine chauffée, un personnel qui sait lire une situation.</p><p>Le dîner est à votre guise, au restaurant 02 de l''hôtel ou en ville. Le lendemain matin, le buffet petit-déjeuner de l''Inbal : fromages artisanaux, poissons, oeufs à la commande, viennoiseries maison, pains au tandoor. Après, la Vieille Ville est toujours là. Le genre de matin qui rend l''heure du départ un peu injuste.</p>'
WHERE slug = 'zipline-jerusalem-inbal';

-- 12. MASTER THE WORLD'S KITCHEN, TEL AVIV
UPDATE experiences2 SET
  title_fr = 'Les cuisines du monde à Tel Aviv',
  subtitle_fr = 'Un cours de cuisine participatif explorant les grandes gastronomies mondiales, suivi d''un séjour à deux pas du boulevard Rothschild au Brown BoBo.',
  long_copy_fr = '<p>Un cours de cuisine en plein coeur de Tel Aviv, jamais le même deux fois. La ville comme décor, la cuisine comme destination.</p><p>On choisit sa cuisine, ou on laisse le chef choisir. Un soir, on fait des pâtes à la main. Un autre, on apprend à rouler des gimbap, à faire gonfler une galette, à monter un falafel correct, à équilibrer une pâte de curry thaï, ou à superposer les épices d''un masala indien. Les cours sont en petits groupes, entièrement participatifs. On cuisine ensemble, on mange ce qu''on a préparé, et on repart avec un savoir-faire qu''on n''avait pas en arrivant.</p><p>Tel Aviv est la bonne ville pour ce genre de cours. Elle se trouve à l''intersection de dizaines de cultures culinaires, et la scène gastronomique reflète cette agitation. Les cours s''appuient sur ce mélange sans prétendre être autre chose qu''une vraie soirée sympa dans une cuisine professionnelle.</p><p>Le Brown BoBo est là pour dormir. C''est un hôtel urbain direct sur la rue Yavne, à quelques pas du boulevard Rothschild, du marché du Carmel et de la rue piétonne Nachalat Binyamin. La terrasse sur le toit a une piscine et un bar à cocktails avec vue ouverte sur la ville.</p><p>Le lendemain matin, un buffet petit-déjeuner kasher laitier dans le salon du lobby. Frais, généreux. Tel Aviv au matin, café à la main, rien d''urgent à faire.</p>'
WHERE slug = 'cooking-class-brown-bobo-tel-aviv';

-- 13. PICNIC ON THE SHORE
UPDATE experiences2 SET
  title_fr = 'Pique-nique sur les rives, Lake House Kinneret',
  subtitle_fr = 'Un pique-nique en bord de lac avec vins et produits locaux, suivi d''un séjour dans une maison au bord du Kinneret avec musique en soirée.',
  long_copy_fr = '<p>Un déjeuner de pique-nique sur les rives du Kinneret. Tout est conçu autour du simple fait d''être au bord de l''eau à midi, avec de la bonne nourriture et du bon vin.</p><p>Le pique-nique est installé sur la plage directement devant Lake House Kinneret. Une couverture est posée sur le sable. Un glacier contient du vin refroidi depuis le matin. La nourriture est préparée fraîche : salade de légumes locaux, pain d''une boulangerie galiléenne, fromage local, houmous au tahini d''un moulin du nord, olives et un simple poisson grillé.</p><p>Le repas n''a pas de structure formelle. On mange ce qu''on veut, quand on veut. Le vin est un blanc de Galilée, choisi parce qu''il ne nécessite ni cérémonie ni commentaire : il est simplement bon, froid et net. L''eau est assez chaude pour se baigner si on le souhaite.</p><p>En fin d''après-midi, le pique-nique est rangé. On retourne à la maison, on se rince les pieds, on se change. Le dîner est à 19h, préparé dans la cuisine de la maison. Les ingrédients sont locaux. La cuisine est simple.</p><p>Après le dîner, il y a souvent de la musique. Un guitariste ou un ensemble se produit dans la salle principale de la maison. La performance est intime. Pas de scène, pas de séparation entre l''interprète et l''auditeur.</p><p>Le lendemain matin, le petit-déjeuner est sur la pelouse face à l''eau. Le rythme du Kinneret continue.</p>'
WHERE slug = 'picnic-on-the-shore-lake-house-kinneret';

-- 14. SUNSET JEEP RIDE TO MOUNT JOASH
UPDATE experiences2 SET
  title_fr = 'Jeep au coucher du soleil, Mont Yoash, Eilat',
  subtitle_fr = 'Une montée en jeep à travers les montagnes d''Eilat au coucher du soleil, avec pita et thé aux herbes sur la crête, suivie d''un séjour au Play Hotel.',
  long_copy_fr = '<p>Une balade en jeep au coucher du soleil dans les montagnes d''Eilat, jusqu''au sommet du mont Yoash. Quatre pays visibles depuis une seule crête, et nulle part ailleurs où être.</p><p>La jeep vous récupère à l''hôtel et prend la direction sud dans le désert. L''itinéraire monte à travers le Nahal Shlomo, le Nahal Rechavam et le Nahal Yehoshaphat, les oueds s''ouvrant et se resserrant au fil de l''altitude. À 725 mètres, le guide s''arrête pour le pique-nique : pita chaud, labneh local, une tasse de thé à la sauge, et la dernière lumière du jour qui se déploie sur la vallée.</p><p>Le guide connaît ces montagnes en profondeur : la géologie, les noms bibliques des ruisseaux, les frontières visibles à l''horizon. Israël, Égypte, Jordanie, Arabie Saoudite, tout en une vue unique. La jeep redescend à mesure que le ciel s''assombrit.</p><p>De retour au Play Hotel, le rythme change totalement. L''hôtel est à quatre minutes à pied de la plage Moriah et de la promenade d''Eilat, compact et attentif, 73 chambres. La terrasse de la piscine extérieure, avec son bar et ses transats, est l''endroit parfait pour décompresser après le désert.</p><p>Le restaurant kasher Varkada, spécialisé dans les poissons, est disponible pour le dîner. Le petit-déjeuner est servi de 7h à 10h30 en buffet. Après une nuit rythmée par la crête du désert et la promenade de la mer Rouge, le matin semble mérité.</p>'
WHERE slug = 'sunset-jeep-mount-joash-play-hotel-eilat';

-- 15. THE SHABBAT YOU NEVER HAD BEFORE
UPDATE experiences2 SET
  title_fr = 'Le Shabbat que vous n''avez jamais vécu',
  subtitle_fr = 'Un Kabbalat Shabbat à quelques minutes de l''hôtel, puis un séjour festif à l''Inbal Jérusalem, à deux pas des remparts de la Vieille Ville.',
  long_copy_fr = '<p>Le Shabbat que vous n''avez jamais vécu, à Jérusalem. Pour les couples, les familles et les groupes d''amis.</p><p>Votre Shabbat commence avant même le check-in. Le vendredi après-midi, pendant que la ville est encore en mouvement, vous rejoignez un Kabbalat Shabbat à quelques minutes de marche de l''hôtel. Le cadre est à ciel ouvert, entouré de la pierre de Jérusalem et de la dernière lumière de la semaine. La musique commence, vivante, des mélodies traditionnelles entremêlées de chansons israéliennes, des voix qui se joignent de toutes parts. Le Lecha Dodi s''élève. Des inconnus deviennent une communauté pour deux heures. Le temps que cela se termine, le Shabbat est déjà arrivé en vous, avant même que vous n''ayez franchi un seuil.</p><p>Puis vous marchez vers l''Inbal. Quelques minutes, pas plus. L''hôtel fait face au parc de la Cloche de la Liberté, avec une vue directe sur les remparts de la Vieille Ville. Le Mur occidental est à dix minutes à pied. Jaffa Gate et le Mont Sion sont encore plus proches.</p><p>Le dîner du vendredi soir est l''événement. La table du Shabbat de l''Inbal attire les habitués de Jérusalem pour une bonne raison : boeuf braisé, poulet rôti, poisson marocain, cholent, un buffet qui porte la mémoire des communautés juives des quatre coins du monde. La salle à manger se remplit d''un bruit du bon genre.</p><p>Le samedi matin, le petit-déjeuner arrive comme une deuxième célébration. Fromages artisanaux, poissons frais, oeufs à la commande, viennoiseries de la boulangerie maison, pains au tandoor pour lesquels les habitués planifient leur retour. Après, la piscine, le spa, ou la Vieille Ville à dix minutes. Le genre de séjour qui remet quelque chose en place.</p>'
WHERE slug = 'shabbat-inbal-jerusalem';

-- 16. WHISKY & CHOCOLATE TASTING
UPDATE experiences2 SET
  title_fr = 'Dégustation whisky et chocolat, Setai Tel Aviv',
  subtitle_fr = 'Une dégustation intime associant whisky de qualité et chocolat artisanal, animée par un sommelier et un chocolatier, dans un cadre privatif au Setai.',
  long_copy_fr = '<p>Une dégustation qui associe whisky et chocolat. La sélection de whiskies traverse les régions et les âges. Les chocolats sont fabriqués par un chocolatier de Tel Aviv qui travaille avec du cacao d''origine unique et un minimum de sucre ajouté. Les mariages sont conçus pour que chaque association révèle quelque chose qu''aucun des deux ne révèlerait seul.</p><p>La dégustation se tient dans une salle privée du Setai, avec vue sur la skyline de Tel Aviv. Le groupe est petit : douze personnes au maximum. Tout le monde est assis à une longue table. Des cartons indiquent quel whisky sera associé à quel chocolat.</p><p>Le sommelier commence par présenter la sélection. Le premier est un single malt écossais, vieilli douze ans, avec des notes de fruits à pépins et de miel. Le chocolatier explique le premier chocolat : cacao d''Équateur, 72 %, avec seulement du beurre de cacao et une pincée de fleur de sel. L''association : d''abord le whisky pour enrober le palais, puis le chocolat, puis une longue pause. L''effet est immédiat. La douceur du chocolat amplifie celle du whisky. L''amertume équilibre la chaleur de l''alcool. Les saveurs semblent créer une troisième saveur, qui n''existe que dans l''espace entre les deux.</p><p>La dégustation continue : un scotch tourbé d''Islay avec un chocolat noir au sel fumé. Un whisky japonais avec un chocolat blanc à la bergamote. Un rye américain avec un chocolat aux éclats de cacao, cardamome et poivre noir. Chaque association est pensée pour surprendre.</p><p>À la fin de la dégustation, qui dure environ quatre-vingt-dix minutes, la pièce est devenue chaleureuse et détendue. Le dîner au Setai est possible ensuite. Les chambres sont modernes, avec vue sur la ville. Le spa et la piscine sont accessibles.</p>'
WHERE slug = 'whisky-chocolate-tasting-setai-tel-aviv';
