-- Correction du formatage HTML des descriptions longues
-- pour les 4 expériences Pereh et Moa insérées en 20260701000000.
-- Le long_copy doit utiliser des balises <p> pour que les paragraphes
-- s'affichent correctement (rendu via dangerouslySetInnerHTML).

UPDATE experiences2 SET
  long_copy = '<p>A farm to table culinary workshop at Pereh, in the Golan Heights. The whole day is built around what the land gave that week.</p>
<p>The morning opens with an outdoor yoga session, gentle and deep, while the Golan air is still cool. At 11:30, the farm to table workshop begins. Chef Yossi Heiv grew up in the Galilee and built his cooking around foraging and what the volcanic soil of the Golan actually produces. The workshop follows the same logic: guests handle the ingredients directly, understand where each one comes from, learn what is in season and why, and see how a dish is constructed from that starting point rather than from a fixed recipe. It is a hands-on session, not a demonstration, and it takes its time.</p>
<p>After the workshop, the afternoon opens up. The infinity pool sits at the heart of the compound, blue stone mosaics, heated through winter, with views toward the grove. The jacuzzi, open to the sky and facing the Naphtali ridge, holds eight guests at sunset. The dry and wet saunas are available for anyone who wants the heat in between. At 16:30, a wine tasting led by the in-house sommelier takes the culinary thread further, in the cellar beneath the lobby, with local cheeses alongside.</p>
<p>Dinner at Rouge Restaurant follows, built from the same seasonal sourcing that ran through the morning''s workshop. Breakfast the next day runs until 11:00 at Rouge, unhurried.</p>',
  long_copy_fr = '<p>Un atelier farm to table au Pereh, dans les hauteurs du Golan. Toute la journée tourne autour de ce que la terre a donné cette semaine-là.</p>
<p>La matinée commence par un cours de yoga en plein air, doux et profond, pendant que l''air du Golan est encore frais. À 11h30, l''atelier commence. Le chef Yossi Heiv a grandi en Galilée et a construit sa cuisine autour de la cueillette sauvage et de ce que le sol volcanique du Golan produit réellement. L''atelier suit la même logique : les participants touchent les ingrédients, comprennent d''où chacun vient, apprennent ce qui est de saison et pourquoi, et voient comment un plat se construit depuis ce point de départ plutôt que depuis une recette figée. C''est une session active, pas une démonstration, et elle prend le temps qu''il faut.</p>
<p>L''après-midi s''ouvre ensuite. La piscine à débordement, carrelée de mosaïque bleue et chauffée en hiver, occupe le cœur du domaine avec vue sur le bois. Le jacuzzi, ouvert sur le ciel et face au massif du Naphtali, accueille jusqu''à huit personnes au coucher du soleil. Les saunas sec et humide sont disponibles pour ceux qui veulent la chaleur entre les deux. À 16h30, une dégustation de vins animée par le sommelier de la maison prolonge le fil culinaire de la journée, dans la cave sous le lobby, avec des fromages locaux accordés.</p>
<p>Le dîner au Rouge suit, construit sur le même approvisionnement saisonnier que l''atelier du matin. Le lendemain, le petit-déjeuner au Rouge est servi jusqu''à 11h, sans pression.</p>'
WHERE slug = 'farm-to-table-workshop-pereh';

UPDATE experiences2 SET
  long_copy = '<p>A sommelier-led wine tasting at Pereh, in the Golan Heights. The afternoon takes place in the cellar. Everything else holds the day around it.</p>
<p>The morning opens with an outdoor yoga session, gentle and deep, while the Golan air is still cool. The rest of the day stays open until the tasting begins at 16:30, in the wine cellar beneath the lobby, kept at the temperature and humidity the bottles need. The sommelier leads guests through a selection of Israeli boutique wines, sourced from producers across the country, presenting each one in its context — the region it comes from, the year, what the soil gave. Local cheeses are chosen to match and served alongside.</p>
<p>The infinity pool, blue stone mosaics and heated through winter, is there for the hours before. So is the jacuzzi, open to the sky, eight guests wide, facing the Naphtali ridge at sunset. The dry and wet saunas sit nearby for anyone who wants them. For guests who want to extend the culinary day even further, the farm to table workshop runs earlier in the morning, a hands-on counterpart to the tasting''s more reflective pace.</p>
<p>Dinner at Rouge Restaurant follows the tasting directly, Chef Yossi Heiv''s kitchen translating the same territorial logic from glass to plate, foraging and seasonal sourcing from the Golan''s volcanic soil. Breakfast the next day runs until 11:00 at Rouge, unhurried.</p>',
  long_copy_fr = '<p>Une dégustation de vins avec le sommelier au Pereh, dans les hauteurs du Golan. Le moment fort de la journée se passe en cave. Le reste tient le cadre autour.</p>
<p>La matinée s''ouvre par un cours de yoga en plein air, doux et profond, pendant que l''air du Golan est encore frais. Le reste de la journée reste libre jusqu''à 16h30, heure à laquelle la dégustation commence dans la cave sous le lobby, maintenue à la température et au taux d''humidité qu''exigent les bouteilles. Le sommelier guide les participants à travers une sélection de vins de domaines israéliens, présentés dans leur contexte : la région d''origine, le millésime, ce que l''année a donné. Des fromages locaux sont choisis pour accompagner.</p>
<p>La piscine à débordement, mosaïque bleue et chauffée en hiver, est là pour les heures qui précèdent. Idem pour le jacuzzi ouvert sur le ciel, face au massif du Naphtali en fin de journée. Les saunas sec et humide sont disponibles à côté. Pour ceux qui veulent prolonger le fil culinaire dès le matin, l''atelier farm to table du chef Yossi Heiv tourne plus tôt dans la journée, version pratique et active de ce que la dégustation explore autrement.</p>
<p>Le dîner au Rouge suit directement la cave, la même logique de territoire traduite du verre à l''assiette, cueillette sauvage et approvisionnement saisonnier depuis le sol volcanique du Golan. Le lendemain, le petit-déjeuner au Rouge est servi jusqu''à 11h, sans se presser.</p>'
WHERE slug = 'wine-tasting-pereh';

UPDATE experiences2 SET
  long_copy = '<p>A fire ritual and sound journey at Moa, in the heart of the Arava. The day moves from breath to flame to silence.</p>
<p>It begins with an outdoor vinyasa session, while the desert light is still low. Then comes the ice bath and breathing workshop in the desert wellness area of the orchard, where two ice baths between 3 and 7 degrees sit alongside a Canadian cedarwood hot tub and a traditional Mexican Temazcal sauna. This is not a treatment that relaxes — it is a contrast that resets the nervous system.</p>
<p>As evening falls, the fire ritual gathers guests around an open flame, a practice rooted in the older rhythms of the desert. The sound journey that follows carries the day into its final hour inside the yurt, a large cooled tent built specifically for meditations and journeys, where sound takes over from everything else.</p>
<p>The night is held by the ecological lake at the center of the property, filtered naturally through vegetation, algae, and specialized soil rather than chemicals, with a stone beach and shaded areas for resting. The restaurant faces west, opening onto the open desert at sunset. The menu changes daily, plant-forward, with fish and proteins drawn from what the kitchen has that evening, alongside a bar serving local Arava wines and desert-inspired cocktails.</p>
<p>The next morning, breakfast is a full buffet, eaten slowly, with the same view as the night before, lit differently.</p>',
  long_copy_fr = '<p>Un rituel du feu et un voyage sonore à Moa, au cœur de l''Arava. La journée passe du souffle à la flamme, puis au silence.</p>
<p>Elle commence par un cours de vinyasa en plein air, pendant que la lumière du désert est encore basse. Puis vient l''atelier de bains froids et de respiration dans l''espace de bien-être du verger, où deux bains de glace entre 3 et 7 degrés jouxtent un jacuzzi en bois de cèdre canadien et un sauna Temazcal de tradition mexicaine. Ce n''est pas un soin qui détend, c''est un contraste qui remet le système nerveux à zéro.</p>
<p>Avec le soir, le rituel du feu rassemble les participants autour d''une flamme ouverte, une pratique ancrée dans les rythmes plus anciens du désert. Le voyage sonore qui suit emmène la journée dans son heure finale à l''intérieur du yurt, une grande tente rafraîchie construite spécifiquement pour les méditations et les journeys, où le son prend le relais de tout le reste.</p>
<p>La nuit est encadrée par le lac écologique au milieu du domaine, filtré naturellement par la végétation, les algues et un sol spécifique plutôt que par des produits chimiques, avec une plage de pierres et des zones d''ombre pour s''allonger. Le restaurant, tourné à l''ouest, ouvre sur le désert ouvert au coucher du soleil. Le menu change chaque jour, centré sur le végétal, avec des poissons et des protéines selon ce que la cuisine a ce soir-là, un bar qui sert des vins de l''Arava et des cocktails inspirés de la flore locale.</p>
<p>Le lendemain matin, le petit-déjeuner est un buffet complet servi lentement, avec la même vue que la veille au soir, éclairée autrement.</p>'
WHERE slug = 'fire-ritual-sound-journey-moa';

UPDATE experiences2 SET
  long_copy = '<p>A couples treatment at Moa, in the Arava. The day builds something together before it settles into stillness.</p>
<p>It starts with an outdoor vinyasa session, then the hot and cold contrasts in the orchard''s wellness area: the Canadian cedarwood hot tub heated to 38 degrees, the two ice baths between 3 and 7 degrees, the Temazcal sauna. This sequence leaves the body fully open before entering the treatment. The desert treatment room receives both guests together, where local therapists work through stress relief and physical support, a space built for two from the start.</p>
<p>The rest of the day belongs to the property. The ecological lake, filtered through vegetation and algae rather than chemicals, with its stone beach and shaded areas for lying down with nothing else to do. The hammocks in the orchard. The yurt for those who want to continue into meditation. In the evening, the fire ritual gathers residents around an open flame for those who want to end the day collectively.</p>
<p>Dinner is served facing the desert as the light fades, a daily-changing menu built around plant proteins and fish, alongside a bar pouring Arava wines and cocktails made from desert flora.</p>
<p>The next morning, the breakfast buffet is eaten slowly with the same desert in front, now in morning light. The kind of stay where you forget to write to anyone.</p>',
  long_copy_fr = '<p>Un soin en couple à Moa, dans l''Arava. La journée construit quelque chose ensemble avant de poser le tempo.</p>
<p>Elle commence par un cours de vinyasa en plein air, puis les contrastes chaud-froid dans l''espace de bien-être du verger : le jacuzzi en cèdre canadien chauffé à 38 degrés, les deux bains de glace entre 3 et 7 degrés, le sauna Temazcal. Ce passage-là laisse le corps pleinement disponible avant d''entrer dans le soin. La salle de soins du désert accueille les deux personnes ensemble, des thérapeutes de la région travaillent sur la libération des tensions et le soutien physique, la pièce pensée pour deux dès le départ.</p>
<p>Le reste de la journée appartient au domaine. Le lac écologique, filtré par la végétation et les algues plutôt que par des produits chimiques, avec sa plage de pierres et ses zones d''ombre pour s''allonger. Les hammacs dans le verger. Le yurt pour ceux qui veulent prolonger dans la méditation. Le soir, le rituel du feu rassemble les résidents autour d''une flamme ouverte pour ceux qui souhaitent terminer la journée collectivement.</p>
<p>Le dîner est servi face au désert qui s''assombrit, un menu qui change chaque jour construit autour du végétal, des poissons et de ce que le marché du matin a donné, avec un bar qui sert des vins de producteurs de l''Arava et des cocktails à base de plantes du désert.</p>
<p>Le lendemain matin, le buffet du petit-déjeuner se mange lentement avec le même désert devant soi, cette fois dans la lumière du matin. Le genre de séjour où on oublie d''écrire à qui que ce soit.</p>'
WHERE slug = 'couples-treatment-moa';
